import { NextResponse } from 'next/server'
import { createClient, createServiceClient } from '@/lib/supabase/server'
import { writeAuditLog } from '@/lib/audit/logger'
import jsPDF from 'jspdf'
import { formatDate } from '@/lib/utils'

interface GenerateBody {
  policy_text: string
  effective_date: string // YYYY-MM-DD
}

function bumpVersion(current: string): string {
  const major = parseInt(current.split('.')[0] ?? '1', 10)
  return `${major + 1}.0`
}

function buildPolicyPDF(
  orgName: string,
  version: string,
  effectiveDate: string,
  policyText: string,
  generatedBy: string
): Buffer {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' })
  const margin = 20
  const pageWidth = 215.9 - margin * 2
  let y = 20

  function checkPage(needed = 10) {
    if (y + needed > 270) { doc.addPage(); y = 20 }
  }

  function addText(text: string, size: number, style: 'normal' | 'bold' = 'normal', indent = 0, color: [number, number, number] = [0, 0, 0]) {
    checkPage(size * 0.7)
    doc.setFontSize(size)
    doc.setFont('helvetica', style)
    doc.setTextColor(...color)
    const lines = doc.splitTextToSize(text, pageWidth - indent)
    doc.text(lines as string[], margin + indent, y)
    y += (lines as string[]).length * (size * 0.45)
  }

  // ── Cover page ────────────────────────────────────────────
  doc.setFillColor(27, 42, 74)
  doc.rect(0, 0, 215.9, 60, 'F')

  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text('KlockCadence', margin, 20)

  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text('TIMEKEEPING POLICY', margin, 38)
  doc.setFontSize(14)
  doc.text('AND PROCEDURES', margin, 48)

  y = 80
  doc.setTextColor(0, 0, 0)

  addText(orgName, 16, 'bold')
  y += 4

  const meta = [
    ['Policy Version:', `Version ${version}`],
    ['Effective Date:', formatDate(effectiveDate)],
    ['Document Type:', 'DCAA-Compliant Timekeeping Policy'],
    ['Generated:', new Date().toLocaleString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })],
    ['Generated by:', generatedBy],
  ]

  for (const [label, value] of meta) {
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(60, 60, 60)
    doc.text(label!, margin, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(0, 0, 0)
    doc.text(value!, margin + 42, y)
    y += 7
  }

  y += 10
  doc.setDrawColor(27, 42, 74)
  doc.setLineWidth(0.5)
  doc.line(margin, y, margin + pageWidth, y)
  y += 8

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  const notice = 'This document is issued pursuant to Defense Contract Audit Agency (DCAA) requirements for federal government contractors. All employees are required to read, understand, and acknowledge this policy before accessing the timekeeping system.'
  const noticeLines = doc.splitTextToSize(notice, pageWidth)
  doc.text(noticeLines as string[], margin, y)
  y += (noticeLines as string[]).length * 5 + 10

  // ── Policy body ────────────────────────────────────────────
  doc.addPage()
  y = 20

  // Parse and render sections from the policy_text
  const sections = policyText.trim().split(/\n\n+/)
  for (const section of sections) {
    const lines = section.trim().split('\n')
    const heading = lines[0] ?? ''
    const body = lines.slice(1).join('\n').trim()

    // Numbered section headings like "1. POLICY STATEMENT"
    if (/^\d+\./.test(heading)) {
      checkPage(16)
      y += 3
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(27, 42, 74)
      const hLines = doc.splitTextToSize(heading, pageWidth)
      doc.text(hLines as string[], margin, y)
      y += (hLines as string[]).length * 5.5
      doc.setTextColor(0, 0, 0)
    } else {
      checkPage(8)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(0, 0, 0)
      const hLines = doc.splitTextToSize(heading, pageWidth)
      doc.text(hLines as string[], margin, y)
      y += (hLines as string[]).length * 5
    }

    if (body) {
      checkPage(8)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(30, 30, 30)
      const bLines = doc.splitTextToSize(body, pageWidth - 4)
      doc.text(bLines as string[], margin + 4, y)
      y += (bLines as string[]).length * 4.5
    }
  }

  // ── Signature / Acknowledgment page ───────────────────────
  doc.addPage()
  y = 20

  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(27, 42, 74)
  doc.text('EMPLOYEE ACKNOWLEDGMENT', margin, y)
  y += 10

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(0, 0, 0)
  const ackText = `I acknowledge that I have received, read, and understand the ${orgName} Timekeeping Policy and Procedures, Version ${version}, effective ${formatDate(effectiveDate)}. I understand that compliance with this policy is a condition of my employment and that violations may result in disciplinary action up to and including termination, and may constitute a violation of the False Claims Act (31 U.S.C. §§ 3729-3733).`
  const ackLines = doc.splitTextToSize(ackText, pageWidth)
  doc.text(ackLines as string[], margin, y)
  y += (ackLines as string[]).length * 4.5 + 16

  const fields = [
    'Employee Full Name (Print)',
    'Employee Signature',
    'Date',
    'Department',
  ]
  for (const field of fields) {
    checkPage(18)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(80, 80, 80)
    doc.text(field, margin, y)
    y += 4
    doc.setDrawColor(0, 0, 0)
    doc.setLineWidth(0.3)
    doc.line(margin, y, margin + pageWidth * 0.65, y)
    y += 12
  }

  y += 8
  doc.setFontSize(8)
  doc.setTextColor(120, 120, 120)
  doc.text(`Generated by KlockCadence · Version ${version} · ${formatDate(effectiveDate)} · Retain for 7 years per FAR 4.703`, margin, y)

  return Buffer.from(doc.output('arraybuffer'))
}

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: profile } = await supabase
    .from('users')
    .select('role, org_id, full_name')
    .eq('id', user.id)
    .single()

  if (!profile || profile.role !== 'admin') {
    return NextResponse.json({ error: 'Admin role required.' }, { status: 403 })
  }

  const body = await request.json() as GenerateBody

  if (!body.policy_text || body.policy_text.trim().length < 100) {
    return NextResponse.json({ error: 'Policy text is required (minimum 100 characters).' }, { status: 422 })
  }
  if (!body.effective_date || !/^\d{4}-\d{2}-\d{2}$/.test(body.effective_date)) {
    return NextResponse.json({ error: 'effective_date is required in YYYY-MM-DD format.' }, { status: 422 })
  }

  const svc = await createServiceClient()

  // Get current org to compute new version
  const { data: org } = await svc
    .from('organizations')
    .select('name, policy_version')
    .eq('id', profile.org_id)
    .single()

  if (!org) return NextResponse.json({ error: 'Organization not found.' }, { status: 404 })

  const newVersion = bumpVersion(org.policy_version as string)

  // Generate PDF
  const pdfBuffer = buildPolicyPDF(
    org.name as string,
    newVersion,
    body.effective_date,
    body.policy_text.trim(),
    profile.full_name
  )

  // Upload to storage
  const storagePath = `${profile.org_id}/v${newVersion}/timekeeping_policy.pdf`
  const { error: uploadError } = await svc.storage
    .from('policy-documents')
    .upload(storagePath, pdfBuffer, { contentType: 'application/pdf', upsert: true })

  if (uploadError) {
    console.error('[policy/generate] upload error:', uploadError.message)
    return NextResponse.json({ error: 'Failed to upload policy PDF.' }, { status: 500 })
  }

  // Insert policy_versions record
  const { data: versionRow, error: versionError } = await svc
    .from('policy_versions')
    .insert({
      org_id: profile.org_id,
      version: newVersion,
      policy_text: body.policy_text.trim(),
      storage_path: storagePath,
      effective_date: body.effective_date,
      created_by: user.id,
    })
    .select('id')
    .single()

  if (versionError) {
    console.error('[policy/generate] version insert error:', versionError.message)
    return NextResponse.json({ error: 'Failed to save policy version record.' }, { status: 500 })
  }

  // Update organization — bumps version, updates text, invalidates all existing acks
  const { error: orgError } = await svc
    .from('organizations')
    .update({
      policy_version: newVersion,
      policy_version_updated_at: new Date().toISOString(),
      policy_text: body.policy_text.trim(),
    })
    .eq('id', profile.org_id)

  if (orgError) {
    console.error('[policy/generate] org update error:', orgError.message)
    return NextResponse.json({ error: 'Failed to update organization policy version.' }, { status: 500 })
  }

  await writeAuditLog({
    org_id: profile.org_id,
    actor_id: user.id,
    action: 'POLICY_VERSION_CREATED',
    target_table: 'policy_versions',
    target_id: (versionRow as { id: string }).id,
    new_value: {
      new_version: newVersion,
      previous_version: org.policy_version,
      effective_date: body.effective_date,
      storage_path: storagePath,
      generated_by: profile.full_name,
      note: 'All employee acknowledgments invalidated. Re-acknowledgment required on next login.',
    },
  })

  return NextResponse.json({
    success: true,
    version: newVersion,
    version_id: (versionRow as { id: string }).id,
    storage_path: storagePath,
  })
}
