import { NextResponse } from 'next/server'
import { createClient, createServiceClient } from '@/lib/supabase/server'
import { writeAuditLog } from '@/lib/audit/logger'
import jsPDF from 'jspdf'
import { formatDate, formatDateTime } from '@/lib/utils'

interface ExportRequest {
  org_id: string
  start_date: string
  end_date: string
  include_timesheets: boolean
  include_leave: boolean
  include_anomalies: boolean
  include_audit_log: boolean
}

export async function POST(request: Request) {
  const supabase = await createClient()
  const serviceSupabase = await createServiceClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: profile } = await supabase
    .from('users')
    .select('role, org_id, full_name')
    .eq('id', user.id)
    .single()

  if (!profile || !['admin', 'finance'].includes(profile.role)) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  const body = await request.json() as ExportRequest

  if (body.org_id !== profile.org_id) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  const { data: org } = await serviceSupabase
    .from('organizations')
    .select('name')
    .eq('id', profile.org_id)
    .single()

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' })
  let y = 20
  const margin = 20
  const pageWidth = 215.9 - margin * 2

  function addSection(text: string) {
    if (y > 250) { doc.addPage(); y = 20 }
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(27, 42, 74)
    doc.text(text, margin, y)
    y += 6
    doc.setTextColor(0, 0, 0)
  }

  function addLine(text: string, indent = 0) {
    if (y > 270) { doc.addPage(); y = 20 }
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(text, pageWidth - indent)
    doc.text(lines as string[], margin + indent, y)
    y += lines.length * 4.5
  }

  function addDivider() {
    if (y > 270) { doc.addPage(); y = 20 }
    doc.setDrawColor(200, 200, 200)
    doc.line(margin, y, margin + pageWidth, y)
    y += 4
  }

  // Cover page
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(27, 42, 74)
  doc.text('DCAA Compliance Audit Package', margin, 50)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(0, 0, 0)
  doc.text(org?.name ?? 'Unknown Organization', margin, 62)
  doc.text(`Period: ${formatDate(body.start_date)} – ${formatDate(body.end_date)}`, margin, 72)
  doc.text(`Generated: ${formatDateTime(new Date().toISOString())}`, margin, 82)
  doc.text(`Generated by: ${profile.full_name} (${profile.role})`, margin, 92)
  doc.setFontSize(9)
  doc.setTextColor(100, 100, 100)
  doc.text(
    'This document is confidential and intended for authorized DCAA audit purposes only.',
    margin, 200
  )
  doc.addPage()
  y = 20

  if (body.include_timesheets) {
    const { data: timesheets } = await serviceSupabase
      .from('timesheets')
      .select('*, users(full_name, email)')
      .eq('org_id', profile.org_id)
      .gte('week_start_date', body.start_date)
      .lte('week_start_date', body.end_date)
      .order('week_start_date')

    addSection('SECTION 1: TIMESHEETS & CERTIFICATIONS')
    addDivider()

    if (timesheets && timesheets.length > 0) {
      for (const ts of timesheets) {
        const u = ts.users as unknown as { full_name: string; email: string } | null
        addLine(`Employee: ${u?.full_name} (${u?.email})`, 4)
        addLine(`Week: ${ts.week_start_date} | Status: ${ts.status.toUpperCase()}`, 4)
        addLine(`Certified: ${ts.certified_by_employee ? `Yes — ${formatDateTime(ts.certified_at ?? '')}` : 'No'}`, 4)
        addLine(`Approved: ${ts.approved_at ? formatDateTime(ts.approved_at) : 'Not approved'}`, 4)
        if (ts.rejection_reason) addLine(`Rejection Reason: ${ts.rejection_reason}`, 4)
        y += 2
      }
    } else {
      addLine('No timesheets found for this period.', 4)
    }
    y += 6
  }

  if (body.include_anomalies) {
    const { data: anomalies } = await serviceSupabase
      .from('anomalies')
      .select('*, users!user_id(full_name)')
      .eq('org_id', profile.org_id)
      .gte('created_at', body.start_date)
      .lte('created_at', body.end_date + 'T23:59:59Z')
      .order('created_at')

    if (y > 240) { doc.addPage(); y = 20 }
    addSection('SECTION 2: COMPLIANCE ANOMALY LOG')
    addDivider()

    if (anomalies && anomalies.length > 0) {
      for (const a of anomalies) {
        const u = a.users as unknown as { full_name: string } | null
        addLine(`[${a.severity.toUpperCase()}] ${a.anomaly_type.replace(/_/g, ' ').toUpperCase()}`, 4)
        addLine(`Employee: ${u?.full_name} | ${formatDateTime(a.created_at)}`, 8)
        addLine(`Description: ${a.description}`, 8)
        addLine(`Resolved: ${a.resolved ? `Yes — ${formatDateTime(a.resolved_at ?? '')}` : 'No'}`, 8)
        y += 2
      }
    } else {
      addLine('No anomalies recorded for this period.', 4)
    }
    y += 6
  }

  if (body.include_audit_log) {
    const { data: logs } = await serviceSupabase
      .from('audit_log')
      .select('*, actor:actor_id(full_name)')
      .eq('org_id', profile.org_id)
      .gte('created_at', body.start_date)
      .lte('created_at', body.end_date + 'T23:59:59Z')
      .order('created_at')
      .limit(1000)

    if (y > 240) { doc.addPage(); y = 20 }
    addSection('SECTION 3: IMMUTABLE AUDIT TRAIL')
    addDivider()

    if (logs && logs.length > 0) {
      for (const log of logs) {
        const actor = log.actor as unknown as { full_name: string } | null
        addLine(`${formatDateTime(log.created_at)} | ${log.action} | ${actor?.full_name ?? 'System'}`, 4)
        addLine(`Target: ${log.target_table} / ${log.target_id} | IP: ${log.ip_address}`, 8)
        y += 1
      }
    } else {
      addLine('No audit log entries for this period.', 4)
    }
  }

  // Log the export in audit trail
  await writeAuditLog({
    org_id: profile.org_id,
    actor_id: user.id,
    action: 'TIMESHEET_CERTIFIED',
    target_table: 'organizations',
    target_id: profile.org_id,
    new_value: { action: 'DCAA_AUDIT_PACKAGE_EXPORTED', start_date: body.start_date, end_date: body.end_date },
  })

  const pdfBuffer = Buffer.from(doc.output('arraybuffer'))

  return new NextResponse(pdfBuffer, {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename="dcaa_audit_package.pdf"',
    },
  })
}
